[feat] project 조회 Redis cache 적용
2023-Console-log/Console-log pull request #355
Opened 2024-09-09 10:28 UTC by wndjs803

- [ ] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [ ] 💯 테스트는 잘 통과했나요?
- [ ] 🏗️ 빌드는 성공했나요?
- [ ] 🧹 불필요한 코드는 제거했나요?
- [ ] 💭 이슈는 등록했나요?
- [ ] 🏷️ 라벨은 등록했나요?
- [ ] 💻 git rebase를 사용했나요?
- [ ] 🌈 알록달록한가요?

## 작업 내용

## 스크린샷

## 주의사항

Closes #{이슈 번호}

2024-11-19 15:26 UTC, heesane requested changes
레거시 코드 제거 및 Transactional 어노테이션 확인

2024-12-17 15:52 UTC, heesane approved these changes
수고하셨습니다!

2024-12-17 15:52 UTC, heesane commented on backend/src/main/java/com/techeerlog/global/config/RedisConfig.java
> +
CacheManager를 Bean으로 등록할 때, 특정 cacheName을 지정하지 않으면, 비즈니스 코드에서 Spring Cache를 사용할 때, 해당 이름을 갖는 설정값을 찾을 수 없기때문에, 별도의 메서드를 통해서 ttl과 같은 설정을 분리하는 것이 좋습니다!

2024-12-17 16:06 UTC, Kiminni approved these changes
고생하셨습니다~

2024-12-17 16:06 UTC, merged